/*
 * Copyright © 2021 Advanced Micro Devices, Inc.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef AC_DRM_FOURCC_H
#define AC_DRM_FOURCC_H

#ifdef _WIN32
#include <stdint.h>
typedef uint64_t __u64;
#define DRM_FORMAT_MOD_VENDOR_NONE    0
#define DRM_FORMAT_MOD_VENDOR_AMD     0x02
#define DRM_FORMAT_RESERVED	      ((1ULL << 56) - 1)
#define fourcc_mod_code(vendor, val) \
	((((__u64)DRM_FORMAT_MOD_VENDOR_## vendor) << 56) | ((val) & 0x00ffffffffffffffULL))
#define DRM_FORMAT_MOD_INVALID	fourcc_mod_code(NONE, DRM_FORMAT_RESERVED)
#define DRM_FORMAT_MOD_LINEAR	fourcc_mod_code(NONE, 0)
#define AMD_FMT_MOD fourcc_mod_code(AMD, 0)
#define IS_AMD_FMT_MOD(val) (((val) >> 56) == DRM_FORMAT_MOD_VENDOR_AMD)
#define AMD_FMT_MOD_TILE_VER_GFX6 0
#define AMD_FMT_MOD_TILE_VER_GFX9 1
#define AMD_FMT_MOD_TILE_VER_GFX10 2
#define AMD_FMT_MOD_TILE_VER_GFX10_RBPLUS 3
#define AMD_FMT_MOD_TILE_VER_GFX11 4
#define AMD_FMT_MOD_TILE_VER_GFX12 5
#define AMD_FMT_MOD_TILE_GFX6_1D_TILED_THIN1 0x2
#define AMD_FMT_MOD_TILE_GFX6_2D_TILED_THIN1 0x4
#define AMD_FMT_MOD_TILE_GFX9_64K_S 9
#define AMD_FMT_MOD_TILE_GFX9_64K_D 10
#define AMD_FMT_MOD_TILE_GFX9_4K_D_X 22
#define AMD_FMT_MOD_TILE_GFX9_64K_S_X 25
#define AMD_FMT_MOD_TILE_GFX9_64K_D_X 26
#define AMD_FMT_MOD_TILE_GFX9_64K_R_X 27
#define AMD_FMT_MOD_TILE_GFX11_256K_R_X 31
#define AMD_FMT_MOD_TILE_GFX12_256B_2D 1
#define AMD_FMT_MOD_TILE_GFX12_4K_2D 2
#define AMD_FMT_MOD_TILE_GFX12_64K_2D 3
#define AMD_FMT_MOD_TILE_GFX12_256K_2D 4
#define AMD_FMT_MOD_DCC_BLOCK_64B 0
#define AMD_FMT_MOD_DCC_BLOCK_128B 1
#define AMD_FMT_MOD_DCC_BLOCK_256B 2
#define AMD_FMT_MOD_TILE_VERSION_SHIFT 0
#define AMD_FMT_MOD_TILE_VERSION_MASK 0xFF
#define AMD_FMT_MOD_TILE_SHIFT 8
#define AMD_FMT_MOD_TILE_MASK 0x1F
#define AMD_FMT_MOD_DCC_SHIFT 13
#define AMD_FMT_MOD_DCC_MASK 0x1
#define AMD_FMT_MOD_DCC_RETILE_SHIFT 14
#define AMD_FMT_MOD_DCC_RETILE_MASK 0x1
#define AMD_FMT_MOD_DCC_PIPE_ALIGN_SHIFT 15
#define AMD_FMT_MOD_DCC_PIPE_ALIGN_MASK 0x1
#define AMD_FMT_MOD_DCC_INDEPENDENT_64B_SHIFT 16
#define AMD_FMT_MOD_DCC_INDEPENDENT_64B_MASK 0x1
#define AMD_FMT_MOD_DCC_INDEPENDENT_128B_SHIFT 17
#define AMD_FMT_MOD_DCC_INDEPENDENT_128B_MASK 0x1
#define AMD_FMT_MOD_DCC_MAX_COMPRESSED_BLOCK_SHIFT 18
#define AMD_FMT_MOD_DCC_MAX_COMPRESSED_BLOCK_MASK 0x3
#define AMD_FMT_MOD_DCC_CONSTANT_ENCODE_SHIFT 20
#define AMD_FMT_MOD_PIPE_XOR_BITS_SHIFT 21
#define AMD_FMT_MOD_BANK_XOR_BITS_SHIFT 24
#define AMD_FMT_MOD_PACKERS_SHIFT 27 /* aliases with BANK_XOR_BITS */
#define AMD_FMT_MOD_RB_SHIFT 30
#define AMD_FMT_MOD_RB_MASK 0x7
#define AMD_FMT_MOD_PIPE_SHIFT 33
#define AMD_FMT_MOD_MICROTILE_SHIFT 14ULL
#define AMD_FMT_MOD_MICROTILE_MASK 0x7
#define AMD_FMT_MOD_MICROTILE_DISPLAY 0x0
#define AMD_FMT_MOD_MICROTILE_THIN 0x1
#define AMD_FMT_MOD_PIPE_CONFIG_SHIFT 17ULL
#define AMD_FMT_MOD_PIPE_CONFIG_MASK 0x1f
#define AMD_FMT_MOD_PIPE_CONFIG_P2 0x0
#define AMD_FMT_MOD_PIPE_CONFIG_P4_8x16 0x4
#define AMD_FMT_MOD_PIPE_CONFIG_P4_16x16 0x5
#define AMD_FMT_MOD_PIPE_CONFIG_P4_16x32 0x6
#define AMD_FMT_MOD_PIPE_CONFIG_P4_32x32 0x7
#define AMD_FMT_MOD_PIPE_CONFIG_P8_16x16_8x16 0x8
#define AMD_FMT_MOD_PIPE_CONFIG_P8_16x32_8x16 0x9
#define AMD_FMT_MOD_PIPE_CONFIG_P8_32x32_8x16 0xa
#define AMD_FMT_MOD_PIPE_CONFIG_P8_16x32_16x16 0xb
#define AMD_FMT_MOD_PIPE_CONFIG_P8_32x32_16x16 0xc
#define AMD_FMT_MOD_PIPE_CONFIG_P8_32x32_16x32 0xd
#define AMD_FMT_MOD_PIPE_CONFIG_P8_32x64_32x32 0xe
#define AMD_FMT_MOD_PIPE_CONFIG_P16_32x32_8x16 0x10
#define AMD_FMT_MOD_PIPE_CONFIG_P16_32x32_16x16 0x11
#define AMD_FMT_MOD_TILE_SPLIT_SHIFT 22ULL
#define AMD_FMT_MOD_TILE_SPLIT_MASK 0x7
#define AMD_FMT_MOD_BANK_WIDTH_SHIFT 25ULL
#define AMD_FMT_MOD_BANK_WIDTH_MASK 0x3
#define AMD_FMT_MOD_BANK_HEIGHT_SHIFT 27ULL
#define AMD_FMT_MOD_BANK_HEIGHT_MASK 0x3
#define AMD_FMT_MOD_MACRO_TILE_ASPECT_SHIFT 29ULL
#define AMD_FMT_MOD_MACRO_TILE_ASPECT_MASK 0x3
#define AMD_FMT_MOD_NUM_BANKS_SHIFT 31ULL
#define AMD_FMT_MOD_NUM_BANKS_MASK 0x3
#define AMD_FMT_MOD_SET(field, value) \
	((uint64_t)(value) << AMD_FMT_MOD_##field##_SHIFT)
#define AMD_FMT_MOD_GET(field, value) \
	(((value) >> AMD_FMT_MOD_##field##_SHIFT) & AMD_FMT_MOD_##field##_MASK)
#else
#include "drm-uapi/drm_fourcc.h"
#endif

#endif /* AC_DRM_FOURCC_H */
