/*
 * Copyright © 2026 Imagination Technologies Ltd.
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * \file pdsc_precomp.c
 *
 * \brief PDS compiler pre-compilation utility.
 */

#include "pdsc.h"
#include "pdsc_internal.h"

#include <assert.h>
#include <ctype.h>
#include <inttypes.h>
#include <libgen.h>
#include <stdio.h>
#include <string.h>

typedef pdsc_program *(*pdsc_precomp_fn_t)(void *mem_ctx,
                                           enum pdsc_feature features);

struct pdsc_precomp_info {
   const char *name;
   pdsc_precomp_fn_t fn;
   enum pdsc_feature feature_variants;
};

#define PRECOMP(_name, _feature_variants)    \
   {                                         \
      .name = #_name,                        \
      .fn = pdsc_##_name##_gen,              \
      .feature_variants = _feature_variants, \
   }
static const struct pdsc_precomp_info pdsc_precomp_infos[] = {};
#undef PRECOMP

static void pdsc_precomp_print_header(FILE *fp, const char *filename, bool hdr)
{
   fputs("/*\n", fp);
   fputs(" * Copyright © 2026 Imagination Technologies Ltd.\n", fp);
   fputs(" *\n", fp);
   fputs(" * SPDX-License-Identifier: MIT\n", fp);
   fputs(" *\n", fp);
   fputs(" * Autogenerated file, do not edit.\n", fp);
   fputs(" */\n", fp);
   fputs("\n", fp);
   fputs("/**\n", fp);
   fprintf(fp, " * \\file %s\n", filename);
   fputs(" *\n", fp);
   fprintf(fp,
           " * \\brief Pre-compiled PDS programs%s.\n",
           hdr ? " header" : "");
   fputs(" */\n", fp);
   fputs("\n", fp);
   fputs("#include <stddef.h>\n", fp);
   fputs("#include <stdint.h>\n", fp);
   fputs("\n", fp);
   if (hdr) {
      fputs("#pragma once\n", fp);
      fputs("\n", fp);
      fputs("static inline unsigned\n", fp);
      fputs("pdsc_precomp_feature_index(enum pdsc_feature feature_variants,\n",
            fp);
      fputs("                           enum pdsc_feature features)\n", fp);
      fputs("{\n", fp);
      fputs("   if (!feature_variants)\n", fp);
      fputs("      return 0;\n", fp);
      fputs("\n", fp);
      fputs("   unsigned index = 0;\n", fp);
      fputs("   for (enum pdsc_feature f = 0; f <= feature_variants; ++f) {\n",
            fp);
      fputs("      /* Skip feature variants we aren't building for. */\n", fp);
      fputs("      if ((f & ~feature_variants) != 0)\n", fp);
      fputs("         continue;\n", fp);
      fputs("\n", fp);
      fputs("      if (f == features)\n", fp);
      fputs("         return index;\n", fp);
      fputs("\n", fp);
      fputs("      ++index;\n", fp);
      fputs("   }\n", fp);
      fputs("\n", fp);
      fputs(
         "   UNREACHABLE(\"Invalid features for provided feature_variants.\");\n",
         fp);
      fputs("}\n", fp);
      fputs("\n", fp);
   }
}

static void pdsc_precomp_print_program_hdr(FILE *fp,
                                           const char *name,
                                           enum pdsc_feature feature_variants)
{
   unsigned num_variants = 1 << util_bitcount(feature_variants);

   fprintf(fp,
           "extern const uint32_t *pdsc_precomp_%s[%u];\n",
           name,
           num_variants);

   fprintf(fp,
           "extern const size_t pdsc_precomp_%s_size[%u];\n\n",
           name,
           num_variants);

   fprintf(
      fp,
      "static inline pdsc_program *pdsc_precomp_%s_variant(void *mem_ctx, enum pdsc_feature features)\n",
      name);
   fputs("{\n", fp);
   fprintf(fp,
           "   unsigned index = pdsc_precomp_feature_index(0x%02" PRIx8
           ", features);\n",
           feature_variants);
   fputs("   struct blob_reader blob;\n", fp);
   fprintf(
      fp,
      "   blob_reader_init(&blob, pdsc_precomp_%s[index], pdsc_precomp_%s_size[index]);\n",
      name,
      name);
   fputs("   return pdsc_deserialize(mem_ctx, &blob);\n", fp);
   fputs("}\n\n", fp);
}

#define PDSC_PRECOMP_COLS 4
static void pdsc_precomp_print_variant_src(FILE *fp,
                                           const struct blob *blob,
                                           const char *name,
                                           unsigned index)
{
   assert(!(blob->size % sizeof(uint32_t)));
   fprintf(fp,
           "const uint32_t pdsc_precomp_%s_%u[%zu] = {",
           name,
           index,
           blob->size / sizeof(uint32_t));
   for (unsigned u = 0; u < blob->size / sizeof(uint32_t); ++u) {
      if (!(u % PDSC_PRECOMP_COLS))
         fputs("\n   ", fp);

      fprintf(fp, "0x%08" PRIx32 ",", ((const uint32_t *)blob->data)[u]);
   }

   fputs("\n};\n", fp);

   fprintf(fp,
           "#define pdsc_precomp_%s_size_%u %zuU\n\n",
           name,
           index,
           blob->size);
}

static void pdsc_precomp_print_program_src(FILE *fp,
                                           const char *name,
                                           enum pdsc_feature feature_variants)
{
   unsigned num_variants = 1 << util_bitcount(feature_variants);

   fprintf(fp, "const uint32_t *pdsc_precomp_%s[%u] = {\n", name, num_variants);

   for (unsigned u = 0; u < num_variants; ++u)
      fprintf(fp, "   pdsc_precomp_%s_%u,\n", name, u);

   fputs("};\n\n", fp);

   fprintf(fp,
           "const size_t pdsc_precomp_%s_size[%u] = {\n",
           name,
           num_variants);

   for (unsigned u = 0; u < num_variants; ++u)
      fprintf(fp, "   pdsc_precomp_%s_size_%u,\n", name, u);

   fputs("};\n\n", fp);
}

int main(int argc, char *argv[argc])
{
   bool test_mode = false;
   if (argc == 1) {
      test_mode = true;
   } else if (argc < 3) {
      fprintf(stderr, "Usage: %s <output header> <output source>\n", argv[0]);
      return 1;
   }

   char *hdr_file = "pdsc_precomp.h";
   char *src_file = "pdsc_precomp.c";
   FILE *fp_hdr = stdout;
   FILE *fp_src = stdout;

   if (!test_mode) {
      hdr_file = argv[1];
      src_file = argv[2];
   }

   if (!test_mode) {
      fp_hdr = fopen(hdr_file, "w");
      if (!fp_hdr) {
         fprintf(stderr, "Failed to open %s\n", hdr_file);
         return 1;
      }

      fp_src = fopen(src_file, "w");
      if (!fp_src) {
         fprintf(stderr, "Failed to open %s\n", src_file);
         goto err_close_hdr;
      }
   }

   pdsc_precomp_print_header(fp_src, basename(src_file), false);
   pdsc_precomp_print_header(fp_hdr, basename(hdr_file), true);

   pdsc_init();

   for (unsigned u = 0; u < ARRAY_SIZE(pdsc_precomp_infos); ++u) {
      const struct pdsc_precomp_info *info = &pdsc_precomp_infos[u];

      pdsc_precomp_print_program_hdr(fp_hdr,
                                     info->name,
                                     info->feature_variants);

      unsigned index = 0;
      struct blob blob;
      pdsc_program *p;
      for (enum pdsc_feature f = 0; f <= info->feature_variants; ++f) {
         /* Skip feature variants we aren't building for. */
         if ((f & ~info->feature_variants) != 0)
            continue;

         p = info->fn(NULL, f);
         pdsc_validate_program(p);
         pdsc_encode_program(p);

         blob_init(&blob);
         pdsc_serialize(&blob, p);
         pdsc_precomp_print_variant_src(fp_src, &blob, info->name, index);
         blob_finish(&blob);

         ralloc_free(p);

         ++index;
      }

      pdsc_precomp_print_program_src(fp_src,
                                     info->name,
                                     info->feature_variants);
   }

   if (!test_mode) {
      fclose(fp_src);
      fclose(fp_hdr);
   }

   return 0;

err_close_hdr:
   fclose(fp_hdr);

   return 1;
}
