/*
 * Copyright (c) 2026 Arm, Ltd.
 * SPDX-License-Identifier: MIT
 */

#include "tflite-ref-ops.h"

#include "tensorflow/lite/c/c_api_experimental.h"

namespace tflite {
namespace ops {
namespace custom {

#define TFLITE_CUSTOM_OP(name) \
   TfLiteRegistration *Register_##name() __attribute__((weak))

TFLITE_CUSTOM_OP(NUMERIC_VERIFY_REF);
TFLITE_CUSTOM_OP(AUDIO_SPECTROGRAM);
TFLITE_CUSTOM_OP(MFCC);
TFLITE_CUSTOM_OP(DETECTION_POSTPROCESS);

#undef TFLITE_CUSTOM_OP

} // namespace custom

namespace builtin {

#define TFLITE_BUILTIN_OP(name) \
   TfLiteRegistration *Register_##name() __attribute__((weak))

TFLITE_BUILTIN_OP(ABS);
TFLITE_BUILTIN_OP(ADD_N);
TFLITE_BUILTIN_OP(ADD_REF);
TFLITE_BUILTIN_OP(ARG_MAX);
TFLITE_BUILTIN_OP(ARG_MIN);
TFLITE_BUILTIN_OP(ASSIGN_VARIABLE);
TFLITE_BUILTIN_OP(ATAN2);
TFLITE_BUILTIN_OP(AVERAGE_POOL_REF);
TFLITE_BUILTIN_OP(BATCH_MATMUL_REF);
TFLITE_BUILTIN_OP(BATCH_TO_SPACE_ND_REF);
TFLITE_BUILTIN_OP(BIDIRECTIONAL_SEQUENCE_LSTM);
TFLITE_BUILTIN_OP(BIDIRECTIONAL_SEQUENCE_RNN);
TFLITE_BUILTIN_OP(BITCAST);
TFLITE_BUILTIN_OP(BITWISE_XOR);
TFLITE_BUILTIN_OP(BROADCAST_ARGS);
TFLITE_BUILTIN_OP(BROADCAST_TO);
TFLITE_BUILTIN_OP(BUCKETIZE);
TFLITE_BUILTIN_OP(CALL_ONCE);
TFLITE_BUILTIN_OP(CAST);
TFLITE_BUILTIN_OP(COMPLEX_ABS);
TFLITE_BUILTIN_OP(CONCATENATION_REF);
TFLITE_BUILTIN_OP(CONVOLUTION_REF);
TFLITE_BUILTIN_OP(CONV_3D_REF);
TFLITE_BUILTIN_OP(CONV_3D_TRANSPOSE_REF);
TFLITE_BUILTIN_OP(COS);
TFLITE_BUILTIN_OP(DENSIFY);
TFLITE_BUILTIN_OP(DEPTHWISE_CONVOLUTION_REF);
TFLITE_BUILTIN_OP(DEPTH_TO_SPACE_REF);
TFLITE_BUILTIN_OP(DEQUANTIZE_REF);
TFLITE_BUILTIN_OP(DIV_REF);
TFLITE_BUILTIN_OP(DYNAMIC_UPDATE_SLICE);
TFLITE_BUILTIN_OP(EMBEDDING_LOOKUP);
TFLITE_BUILTIN_OP(EMBEDDING_LOOKUP_SPARSE);
TFLITE_BUILTIN_OP(EQUAL);
TFLITE_BUILTIN_OP(EXPAND_DIMS);
TFLITE_BUILTIN_OP(EXP_REF);
TFLITE_BUILTIN_OP(FAKE_QUANT_REF);
TFLITE_BUILTIN_OP(FILL);
TFLITE_BUILTIN_OP(FLOOR);
TFLITE_BUILTIN_OP(FLOOR_DIV);
TFLITE_BUILTIN_OP(FLOOR_MOD);
TFLITE_BUILTIN_OP(FLOOR_REF);
TFLITE_BUILTIN_OP(FULLY_CONNECTED_REF);
TFLITE_BUILTIN_OP(GATHER);
TFLITE_BUILTIN_OP(GATHER_ND);
TFLITE_BUILTIN_OP(GELU);
TFLITE_BUILTIN_OP(GREATER);
TFLITE_BUILTIN_OP(GREATER_EQUAL);
TFLITE_BUILTIN_OP(HARD_SWISH_REF);
TFLITE_BUILTIN_OP(HASHTABLE_LOOKUP);
TFLITE_BUILTIN_OP(IF);
TFLITE_BUILTIN_OP(IMAG);
TFLITE_BUILTIN_OP(LEAKY_RELU_REF);
TFLITE_BUILTIN_OP(LESS);
TFLITE_BUILTIN_OP(LESS_EQUAL);
TFLITE_BUILTIN_OP(LOCAL_RESPONSE_NORM_REF);
TFLITE_BUILTIN_OP(LOG);
TFLITE_BUILTIN_OP(LOGICAL_AND);
TFLITE_BUILTIN_OP(LOGICAL_NOT);
TFLITE_BUILTIN_OP(LOGICAL_OR);
TFLITE_BUILTIN_OP(LOGISTIC_REF);
TFLITE_BUILTIN_OP(LOG_SOFTMAX_REF);
TFLITE_BUILTIN_OP(LSH_PROJECTION);
TFLITE_BUILTIN_OP(LSTM);
TFLITE_BUILTIN_OP(L2NORM_REF);
TFLITE_BUILTIN_OP(L2_POOL_REF);
TFLITE_BUILTIN_OP(MATRIX_DIAG);
TFLITE_BUILTIN_OP(MATRIX_SET_DIAG);
TFLITE_BUILTIN_OP(MAXIMUM_REF);
TFLITE_BUILTIN_OP(MAX_POOL_REF);
TFLITE_BUILTIN_OP(MEAN_REF);
TFLITE_BUILTIN_OP(MINIMUM_REF);
TFLITE_BUILTIN_OP(MIRROR_PAD);
TFLITE_BUILTIN_OP(MUL_REF);
TFLITE_BUILTIN_OP(MULTINOMIAL);
TFLITE_BUILTIN_OP(NEG);
TFLITE_BUILTIN_OP(NON_MAX_SUPPRESSION_V4);
TFLITE_BUILTIN_OP(NON_MAX_SUPPRESSION_V5);
TFLITE_BUILTIN_OP(NOT_EQUAL);
TFLITE_BUILTIN_OP(ONE_HOT);
TFLITE_BUILTIN_OP(PACK);
TFLITE_BUILTIN_OP(PADV2_REF);
TFLITE_BUILTIN_OP(PAD_REF);
TFLITE_BUILTIN_OP(POW);
TFLITE_BUILTIN_OP(PRELU_REF);
TFLITE_BUILTIN_OP(QUANTIZE_REF);
TFLITE_BUILTIN_OP(RANDOM_STANDARD_NORMAL);
TFLITE_BUILTIN_OP(RANDOM_UNIFORM);
TFLITE_BUILTIN_OP(RANGE);
TFLITE_BUILTIN_OP(RANK);
TFLITE_BUILTIN_OP(READ_VARIABLE);
TFLITE_BUILTIN_OP(REAL);
TFLITE_BUILTIN_OP(REDUCE_ALL_REF);
TFLITE_BUILTIN_OP(REDUCE_ANY_REF);
TFLITE_BUILTIN_OP(REDUCE_MAX_REF);
TFLITE_BUILTIN_OP(REDUCE_MIN_REF);
TFLITE_BUILTIN_OP(REDUCE_PROD_REF);
TFLITE_BUILTIN_OP(RELU);
TFLITE_BUILTIN_OP(RELU6);
TFLITE_BUILTIN_OP(RELU_0_TO_1);
TFLITE_BUILTIN_OP(RELU_N1_TO_1);
TFLITE_BUILTIN_OP(RESHAPE);
TFLITE_BUILTIN_OP(RESIZE_BILINEAR_REF);
TFLITE_BUILTIN_OP(RESIZE_NEAREST_NEIGHBOR_REF);
TFLITE_BUILTIN_OP(REVERSE_SEQUENCE);
TFLITE_BUILTIN_OP(REVERSE_V2);
TFLITE_BUILTIN_OP(RIGHT_SHIFT);
TFLITE_BUILTIN_OP(RNN);
TFLITE_BUILTIN_OP(RSQRT);
TFLITE_BUILTIN_OP(SCATTER_ND);
TFLITE_BUILTIN_OP(SELECT);
TFLITE_BUILTIN_OP(SELECT_V2);
TFLITE_BUILTIN_OP(SHAPE);
TFLITE_BUILTIN_OP(SIGN);
TFLITE_BUILTIN_OP(SIN);
TFLITE_BUILTIN_OP(SKIP_GRAM);
TFLITE_BUILTIN_OP(SLICE_REF);
TFLITE_BUILTIN_OP(SOFTMAX_REF);
TFLITE_BUILTIN_OP(SPACE_TO_BATCH_ND_REF);
TFLITE_BUILTIN_OP(SPACE_TO_DEPTH_REF);
TFLITE_BUILTIN_OP(SPARSE_TO_DENSE);
TFLITE_BUILTIN_OP(SPLIT);
TFLITE_BUILTIN_OP(SPLIT_V);
TFLITE_BUILTIN_OP(SQRT);
TFLITE_BUILTIN_OP(SQUARE);
TFLITE_BUILTIN_OP(SQUARED_DIFFERENCE);
TFLITE_BUILTIN_OP(SQUEEZE);
TFLITE_BUILTIN_OP(STRIDED_SLICE_REF);
TFLITE_BUILTIN_OP(SUB_REF);
TFLITE_BUILTIN_OP(SUM_REF);
TFLITE_BUILTIN_OP(SVDF);
TFLITE_BUILTIN_OP(TANH_REF);
TFLITE_BUILTIN_OP(TILE);
TFLITE_BUILTIN_OP(TOPK_V2);
TFLITE_BUILTIN_OP(TRANSPOSECONV_REF);
TFLITE_BUILTIN_OP(TRANSPOSE_REF);
TFLITE_BUILTIN_OP(UNIDIRECTIONAL_SEQUENCE_LSTM);
TFLITE_BUILTIN_OP(UNIDIRECTIONAL_SEQUENCE_RNN);
TFLITE_BUILTIN_OP(UNIQUE);
TFLITE_BUILTIN_OP(UNPACK);
TFLITE_BUILTIN_OP(UNSORTED_SEGMENT_MAX);
TFLITE_BUILTIN_OP(UNSORTED_SEGMENT_MIN);
TFLITE_BUILTIN_OP(UNSORTED_SEGMENT_PROD);
TFLITE_BUILTIN_OP(UNSORTED_SEGMENT_SUM);
TFLITE_BUILTIN_OP(VAR_HANDLE);
TFLITE_BUILTIN_OP(WHERE);
TFLITE_BUILTIN_OP(WHILE);
TFLITE_BUILTIN_OP(ZEROS_LIKE);

#undef TFLITE_BUILTIN_OP

} // namespace builtin
} // namespace ops
} // namespace tflite

static void
add_builtin_op(TfLiteInterpreterOptions *options,
               TfLiteBuiltinOperator op,
               TfLiteRegistration *(*registration)(void),
               int min_version,
               int max_version)
{
   if (!registration)
      return;

   TfLiteInterpreterOptionsAddBuiltinOp(options, op, registration(),
                                        min_version, max_version);
}

static void
add_custom_op(TfLiteInterpreterOptions *options,
              const char *name,
              TfLiteRegistration *(*registration)(void))
{
   if (!registration)
      return;

   TfLiteInterpreterOptionsAddCustomOp(options, name, registration(), 1, 1);
}

#define ADD_BUILTIN(op, registration, min_version, max_version) \
   add_builtin_op(options, kTfLiteBuiltin##op, \
                  tflite::ops::builtin::Register_##registration, \
                  min_version, max_version)

#define ADD_CUSTOM(name, registration) \
   add_custom_op(options, name, tflite::ops::custom::Register_##registration)

void
tflite_register_ref_ops(TfLiteInterpreterOptions *options)
{
   ADD_BUILTIN(Abs, ABS, 1, 3);
   ADD_BUILTIN(HardSwish, HARD_SWISH_REF, 1, 1);
   ADD_BUILTIN(Relu, RELU, 1, 3);
   ADD_BUILTIN(ReluN1To1, RELU_N1_TO_1, 1, 1);
   ADD_BUILTIN(Relu0To1, RELU_0_TO_1, 1, 1);
   ADD_BUILTIN(Relu6, RELU6, 1, 3);
   ADD_BUILTIN(Tanh, TANH_REF, 1, 3);
   ADD_BUILTIN(Logistic, LOGISTIC_REF, 1, 3);
   ADD_BUILTIN(AveragePool2d, AVERAGE_POOL_REF, 1, 3);
   ADD_BUILTIN(MaxPool2d, MAX_POOL_REF, 1, 3);
   ADD_BUILTIN(L2Pool2d, L2_POOL_REF, 1, 1);
   ADD_BUILTIN(Conv2d, CONVOLUTION_REF, 1, 6);
   ADD_BUILTIN(DepthwiseConv2d, DEPTHWISE_CONVOLUTION_REF, 1, 6);
   ADD_BUILTIN(Svdf, SVDF, 1, 4);
   ADD_BUILTIN(Rnn, RNN, 1, 3);
   ADD_BUILTIN(BidirectionalSequenceRnn, BIDIRECTIONAL_SEQUENCE_RNN, 1, 3);
   ADD_BUILTIN(UnidirectionalSequenceRnn, UNIDIRECTIONAL_SEQUENCE_RNN, 1, 3);
   ADD_BUILTIN(EmbeddingLookup, EMBEDDING_LOOKUP, 1, 3);
   ADD_BUILTIN(EmbeddingLookupSparse, EMBEDDING_LOOKUP_SPARSE, 1, 1);
   ADD_BUILTIN(FullyConnected, FULLY_CONNECTED_REF, 1, 9);
   ADD_BUILTIN(LshProjection, LSH_PROJECTION, 1, 1);
   ADD_BUILTIN(HashtableLookup, HASHTABLE_LOOKUP, 1, 1);
   ADD_BUILTIN(Softmax, SOFTMAX_REF, 1, 3);
   ADD_BUILTIN(Concatenation, CONCATENATION_REF, 1, 3);
   ADD_BUILTIN(Add, ADD_REF, 1, 5);
   ADD_BUILTIN(SpaceToBatchNd, SPACE_TO_BATCH_ND_REF, 1, 4);
   ADD_BUILTIN(BatchToSpaceNd, BATCH_TO_SPACE_ND_REF, 1, 4);
   ADD_BUILTIN(Mul, MUL_REF, 1, 7);
   ADD_BUILTIN(L2Normalization, L2NORM_REF, 1, 2);
   ADD_BUILTIN(BroadcastTo, BROADCAST_TO, 2, 3);
   ADD_BUILTIN(LocalResponseNormalization, LOCAL_RESPONSE_NORM_REF, 1, 1);
   ADD_BUILTIN(Lstm, LSTM, 1, 4);
   ADD_BUILTIN(BidirectionalSequenceLstm, BIDIRECTIONAL_SEQUENCE_LSTM, 1, 3);
   ADD_BUILTIN(UnidirectionalSequenceLstm, UNIDIRECTIONAL_SEQUENCE_LSTM, 1, 3);
   ADD_BUILTIN(Pad, PAD_REF, 1, 4);
   ADD_BUILTIN(Padv2, PADV2_REF, 1, 4);
   ADD_BUILTIN(Reshape, RESHAPE, 1, 1);
   ADD_BUILTIN(ResizeBilinear, RESIZE_BILINEAR_REF, 1, 4);
   ADD_BUILTIN(ResizeNearestNeighbor, RESIZE_NEAREST_NEIGHBOR_REF, 1, 4);
   ADD_BUILTIN(SkipGram, SKIP_GRAM, 1, 1);
   ADD_BUILTIN(SpaceToDepth, SPACE_TO_DEPTH_REF, 1, 2);
   ADD_BUILTIN(DepthToSpace, DEPTH_TO_SPACE_REF, 1, 1);
   ADD_BUILTIN(Gather, GATHER, 1, 6);
   ADD_BUILTIN(Transpose, TRANSPOSE_REF, 1, 5);
   ADD_BUILTIN(Mean, MEAN_REF, 1, 3);
   ADD_BUILTIN(Div, DIV_REF, 1, 2);
   ADD_BUILTIN(Sub, SUB_REF, 1, 5);
   ADD_BUILTIN(Split, SPLIT, 1, 4);
   ADD_BUILTIN(SplitV, SPLIT_V, 1, 2);
   ADD_BUILTIN(Squeeze, SQUEEZE, 1, 1);
   ADD_BUILTIN(StridedSlice, STRIDED_SLICE_REF, 1, 4);
   ADD_BUILTIN(Exp, EXP_REF, 1, 2);
   ADD_BUILTIN(TopkV2, TOPK_V2, 1, 3);
   ADD_BUILTIN(Log, LOG, 1, 1);
   ADD_BUILTIN(LogSoftmax, LOG_SOFTMAX_REF, 1, 2);
   ADD_BUILTIN(Cast, CAST, 1, 4);
   ADD_BUILTIN(Dequantize, DEQUANTIZE_REF, 1, 4);
   ADD_BUILTIN(Prelu, PRELU_REF, 1, 1);
   ADD_BUILTIN(Maximum, MAXIMUM_REF, 1, 4);
   ADD_BUILTIN(Minimum, MINIMUM_REF, 1, 4);
   ADD_BUILTIN(ArgMax, ARG_MAX, 1, 2);
   ADD_BUILTIN(ArgMin, ARG_MIN, 1, 2);
   ADD_BUILTIN(Greater, GREATER, 1, 2);
   ADD_BUILTIN(GreaterEqual, GREATER_EQUAL, 1, 3);
   ADD_BUILTIN(Less, LESS, 1, 3);
   ADD_BUILTIN(LessEqual, LESS_EQUAL, 1, 2);
   ADD_BUILTIN(Floor, FLOOR_REF, 1, 1);
   ADD_BUILTIN(Neg, NEG, 1, 1);
   ADD_BUILTIN(Select, SELECT, 1, 2);
   ADD_BUILTIN(SelectV2, SELECT_V2, 1, 1);
   ADD_BUILTIN(Slice, SLICE_REF, 1, 5);
   ADD_BUILTIN(Sin, SIN, 1, 1);
   ADD_BUILTIN(Cos, COS, 1, 1);
   ADD_BUILTIN(TransposeConv, TRANSPOSECONV_REF, 1, 3);
   ADD_BUILTIN(Tile, TILE, 1, 2);
   ADD_BUILTIN(Sum, SUM_REF, 1, 2);
   ADD_BUILTIN(ReduceProd, REDUCE_PROD_REF, 1, 2);
   ADD_BUILTIN(ReduceMax, REDUCE_MAX_REF, 1, 3);
   ADD_BUILTIN(ReduceMin, REDUCE_MIN_REF, 1, 3);
   ADD_BUILTIN(ReduceAny, REDUCE_ANY_REF, 1, 1);
   ADD_BUILTIN(ReduceAll, REDUCE_ALL_REF, 1, 1);
   ADD_BUILTIN(ExpandDims, EXPAND_DIMS, 1, 1);
   ADD_BUILTIN(SparseToDense, SPARSE_TO_DENSE, 1, 3);
   ADD_BUILTIN(Equal, EQUAL, 1, 4);
   ADD_BUILTIN(NotEqual, NOT_EQUAL, 1, 3);
   ADD_BUILTIN(Sqrt, SQRT, 1, 1);
   ADD_BUILTIN(Rsqrt, RSQRT, 1, 2);
   ADD_BUILTIN(Shape, SHAPE, 1, 1);
   ADD_BUILTIN(Rank, RANK, 1, 1);
   ADD_BUILTIN(Pow, POW, 1, 1);
   ADD_BUILTIN(FakeQuant, FAKE_QUANT_REF, 1, 2);
   ADD_BUILTIN(Pack, PACK, 1, 3);
   ADD_BUILTIN(OneHot, ONE_HOT, 1, 1);
   ADD_BUILTIN(LogicalOr, LOGICAL_OR, 1, 1);
   ADD_BUILTIN(LogicalAnd, LOGICAL_AND, 1, 1);
   ADD_BUILTIN(LogicalNot, LOGICAL_NOT, 1, 1);
   ADD_BUILTIN(Unpack, UNPACK, 1, 4);
   ADD_BUILTIN(FloorDiv, FLOOR_DIV, 1, 3);
   ADD_BUILTIN(Square, SQUARE, 1, 1);
   ADD_BUILTIN(ZerosLike, ZEROS_LIKE, 1, 1);
   ADD_BUILTIN(FloorMod, FLOOR_MOD, 1, 2);
   ADD_BUILTIN(Range, RANGE, 1, 1);
   ADD_BUILTIN(LeakyRelu, LEAKY_RELU_REF, 1, 2);
   ADD_BUILTIN(SquaredDifference, SQUARED_DIFFERENCE, 1, 2);
   ADD_BUILTIN(Fill, FILL, 1, 3);
   ADD_BUILTIN(MirrorPad, MIRROR_PAD, 1, 3);
   ADD_BUILTIN(Unique, UNIQUE, 1, 1);
   ADD_BUILTIN(ReverseV2, REVERSE_V2, 1, 2);
   ADD_BUILTIN(AddN, ADD_N, 1, 1);
   ADD_BUILTIN(GatherNd, GATHER_ND, 1, 4);
   ADD_BUILTIN(Where, WHERE, 1, 2);
   ADD_BUILTIN(ReverseSequence, REVERSE_SEQUENCE, 1, 1);
   ADD_BUILTIN(MatrixDiag, MATRIX_DIAG, 1, 1);
   ADD_BUILTIN(Quantize, QUANTIZE_REF, 1, 2);
   ADD_BUILTIN(MatrixSetDiag, MATRIX_SET_DIAG, 1, 1);
   ADD_BUILTIN(If, IF, 1, 1);
   ADD_BUILTIN(While, WHILE, 1, 1);
   ADD_BUILTIN(NonMaxSuppressionV4, NON_MAX_SUPPRESSION_V4, 1, 1);
   ADD_BUILTIN(NonMaxSuppressionV5, NON_MAX_SUPPRESSION_V5, 1, 1);
   ADD_BUILTIN(ScatterNd, SCATTER_ND, 1, 1);
   ADD_BUILTIN(Densify, DENSIFY, 1, 1);
   ADD_BUILTIN(BatchMatmul, BATCH_MATMUL_REF, 1, 3);
   ADD_BUILTIN(Conv3d, CONV_3D_REF, 1, 1);
   ADD_BUILTIN(Imag, IMAG, 1, 1);
   ADD_BUILTIN(Real, REAL, 1, 1);
   ADD_BUILTIN(ComplexAbs, COMPLEX_ABS, 1, 1);
   ADD_BUILTIN(Conv3dTranspose, CONV_3D_TRANSPOSE_REF, 1, 1);
   ADD_BUILTIN(BroadcastArgs, BROADCAST_ARGS, 1, 1);
   ADD_BUILTIN(Multinomial, MULTINOMIAL, 1, 1);
   ADD_BUILTIN(RandomStandardNormal, RANDOM_STANDARD_NORMAL, 1, 1);
   ADD_BUILTIN(Bucketize, BUCKETIZE, 1, 1);
   ADD_BUILTIN(RandomUniform, RANDOM_UNIFORM, 1, 1);
   ADD_BUILTIN(Gelu, GELU, 1, 2);
   ADD_BUILTIN(DynamicUpdateSlice, DYNAMIC_UPDATE_SLICE, 1, 1);
   ADD_BUILTIN(UnsortedSegmentProd, UNSORTED_SEGMENT_PROD, 1, 1);
   ADD_BUILTIN(UnsortedSegmentMax, UNSORTED_SEGMENT_MAX, 1, 1);
   ADD_BUILTIN(UnsortedSegmentMin, UNSORTED_SEGMENT_MIN, 1, 1);
   ADD_BUILTIN(UnsortedSegmentSum, UNSORTED_SEGMENT_SUM, 1, 1);
   ADD_BUILTIN(Atan2, ATAN2, 1, 1);
   ADD_BUILTIN(Sign, SIGN, 1, 1);
   ADD_BUILTIN(CallOnce, CALL_ONCE, 1, 1);
   ADD_BUILTIN(VarHandle, VAR_HANDLE, 1, 1);
   ADD_BUILTIN(ReadVariable, READ_VARIABLE, 1, 1);
   ADD_BUILTIN(AssignVariable, ASSIGN_VARIABLE, 1, 1);
   ADD_BUILTIN(Bitcast, BITCAST, 1, 1);
   ADD_BUILTIN(BitwiseXor, BITWISE_XOR, 1, 1);
   ADD_BUILTIN(RightShift, RIGHT_SHIFT, 1, 1);

   ADD_CUSTOM("NumericVerify", NUMERIC_VERIFY_REF);
   ADD_CUSTOM("Mfcc", MFCC);
   ADD_CUSTOM("AudioSpectrogram", AUDIO_SPECTROGRAM);
   ADD_CUSTOM("TFLite_Detection_PostProcess", DETECTION_POSTPROCESS);
}

#undef ADD_CUSTOM
#undef ADD_BUILTIN
