[[fluster]]
bin = "/fluster/fluster.py"
decoders = [
  # "GStreamer-AV1-Vulkan", # uncomment when updating to gstreamer >= 1.28
  # "GStreamer-VP9-Vulkan", # uncomment when updating to gstreamer >= 1.28
  "GStreamer-H.264-Vulkan",
  "GStreamer-H.265-Vulkan",
]
