[traces_db]
download_url = "https://s3.freedesktop.org/mesa-tracie-public/"

[[traces]]
path = "unigine/sanctuary-d3d9.trace-dxgi"
# This trace is not trimmed to a single frame, so it takes too long to render.

[[traces]]
path = "unigine/tropics-d3d9.trace-dxgi"
# This trace is not trimmed to a single frame, so it takes too long to render.

# Note that all the unigine/heaven traces crash when using --loops=
[[traces]]
path = "unigine/heaven-scene1-low-d3d9.trace-dxgi"
nonloopable = true
devices = { lvp = { checksum = "555efa5bcc89a638ed58df874aa13d0727bc7e798bfd9b42b2aa1854e3447688" } }

[[traces]]
path = "unigine/heaven-scene1-low-d3d11.trace-dxgi"
nonloopable = true
devices = { lvp = { checksum = "9ab7ad92594c3ec45ebdea32c28f21c3b5f05518d56468be53ecd31fb4c2e2e8" } }

[[traces]]
path = "unigine/heaven-scene1-ultra-d3d11.trace-dxgi"
nonloopable = true
devices = { lvp = { checksum = "aa114d950a0f32ea729e71c772b704f5b2d4b5063c7ab3a44c7a919b32d52066" } }

[[traces]]
path = "unigine/heaven-scene12-low-d3d9.trace-dxgi"
nonloopable = true
devices = { lvp = { checksum = "9f6586cd18b7add22d8d17b283b03e0e669b5cbcb3199d2cc655f5dde0d753df" } }

[[traces]]
path = "unigine/heaven-scene12-ultra-d3d11.trace-dxgi"
nonloopable = true
devices = { lvp = { checksum = "e742c05cdabcbaa634fe2607b642fbd16edc944e820009271fd70edd7ace46dd" } }

[[traces]]
path = "./LunarG-VulkanSamples/amd/polaris10/Hologram:-w:640:-h:480.gfxr"
devices = { lvp = { checksum = "13a59c0dc941b1ef954d6b55b43bc458791c41fd7056d98a1f5bb9bb74b9e0a6" } }
