.imagination-rules:
  stage: imagination
  rules:
    - !reference [.test, rules]
    - !reference [.imagination-farm-rules, rules]
    - !reference [.vulkan-rules, rules]
    - changes: &imagination_file_list
        - src/imagination/*
        - src/imagination/ci/gitlab-ci.yml
        - src/imagination/ci/gitlab-ci-inc.yml
        - src/imagination/ci/deqp-$DEQP_SUITE.toml
        - src/imagination/ci/$GPU_VERSION-fails.txt
        - src/imagination/ci/$GPU_VERSION-flakes.txt
        - src/imagination/ci/$GPU_VERSION-skips.txt
        - src/imagination/common/**/*
        - src/imagination/csbgen/**/*
        - src/imagination/include/**/*
        - src/imagination/pco/**/*
        - src/imagination/vulkan/**/*
      when: on_success

.imagination-manual-rules:
  stage: imagination-nightly
  extends: .no-auto-retry
  rules:
    - !reference [.test, rules]
    - !reference [.imagination-farm-manual-rules, rules]
    - !reference [.vulkan-manual-rules, rules]
    - changes:
        *imagination_file_list
      when: manual

.imagination-ci-tron:
  extends:
    - .ci-tron-b2c-diskless-v1
  variables:
    RUNNER_FARM_LOCATION: imagination
    CI_TRON_TIMEOUT__FIRST_CONSOLE_ACTIVITY__MINUTES: 0.5
    CI_TRON_TIMEOUT__FIRST_CONSOLE_ACTIVITY__RETRIES: 3
    CI_TRON_DUT_SETUP_TAGS: $GPU_VENDOR_TAG,$GPU_MODEL_TAG
  tags:
    - ci-tron:priority:$CI_TRON_JOB_PRIORITY
    - $GPU_VENDOR_TAG
    - $GPU_MODEL_TAG

# 12 devices
.imagination-ti-am68-sk:arm64:
  extends:
    - .imagination-ci-tron
  parallel: 12
  variables:
    B2C_VERSION: v0.9.18
    CI_TRON_DTB__0__URL: 'https://gitlab.freedesktop.org/gfx-ci/boot2container/-/releases/$B2C_VERSION/downloads/linux-arm64.dtbs.cpio.xz'
    CI_TRON_DTB__0__FORMAT__0__ARCHIVE__MATCH: boot/dtbs/ti/k3-am68-sk-base-board.dtb
    CI_TRON__B2C_DISKLESS_IMAGESTORE_PLATFORM: linux/arm64/v8
    GPU_VENDOR_TAG: dt_gpu:vendor:ti
    GPU_MODEL_TAG: dt_gpu:model:j721s2-gpu
    GPU_VERSION: bxs-4-64
    FDO_CI_CONCURRENT: 3
