        and (1)                   cr0           cr0<0>            0xfffffb3f      {Switch}
        and (1)                   cr0           cr0<0>            0xffffff3f      {Switch}
        and (1)                   cr0           cr0<0>            0xfffffb7f      {Switch}
        and (1)                   cr0           cr0<0>            0xffffff7f      {Switch}
        and (1)                   cr0           cr0<0>            0xfffffbbf      {Switch}
        and (1)                   cr0           cr0<0>            0xffffffbf      {Switch}
        and (1)                   cr0           cr0<0>            0xffffffcf      {Switch}
        and (1)                   cr0           cr0<0>            0xfffffbff      {Switch}
        or (1)                    cr0           cr0<0>            0x00000400      {Switch}
        or (1)                    cr0           cr0<0>            0x00000030      {Switch}
        or (1)                    cr0           cr0<0>            0x00000040      {Switch}
        or (1)                    cr0           cr0<0>            0x00000440      {Switch}
        or (1)                    cr0           cr0<0>            0x00000080      {Switch}
        or (1)                    cr0           cr0<0>            0x00000480      {Switch}
