(W)     sync.nop (16)                           null                              {@1}
(W)     sync.nop (1)                            null                              {@1}
(W)     sync.nop (1)                            null                              {@2}
(W)     sync.nop (1)                            null                              {@3}
(W)     sync.nop (1)                            null                              {@4}
(W)     sync.nop (1)                            null                              {@5}
(W)     sync.nop (1)                            null                              {@6}
(W)     sync.nop (1)                            null                              {@7}
(W)     sync.nop (1|M8)                         null                              {@1}
(W)     sync.nop (1|M8)                         null                              {@2}
(W)     sync.nop (1|M8)                         null                              {@3}
(W)     sync.nop (1|M8)                         null                              {@4}
(W)     sync.nop (1|M8)                         null                              {@5}
(W)     sync.nop (1|M8)                         null                              {@6}
(W)     sync.nop (1|M8)                         null                              {@7}
(W)     sync.nop (1|M16)                        null                              {@1}
(W)     sync.nop (1|M16)                        null                              {@2}
(W)     sync.nop (1|M16)                        null                              {@3}
(W)     sync.nop (1|M16)                        null                              {@4}
(W)     sync.nop (1|M16)                        null                              {@5}
(W)     sync.nop (1|M16)                        null                              {@6}
(W)     sync.nop (1|M16)                        null                              {@7}
(W)     sync.nop (1|M24)                        null                              {@1}
(W)     sync.nop (1|M24)                        null                              {@2}
(W)     sync.nop (1|M24)                        null                              {@3}
(W)     sync.nop (1|M24)                        null                              {@4}
(W)     sync.nop (1|M24)                        null                              {@5}
(W)     sync.nop (1|M24)                        null                              {@6}
(W)     sync.nop (1|M24)                        null                              {@7}
(W)     sync.nop (32)                           null                              {@1}
(W)     sync.nop (8)                            null                              {@1}
        sync.allwr (16)                         null
        sync.allwr (8)                          null
